[project]
name = "mdsthin"
description = "MDSplus Thin-Client implemented in pure python"
version = "1.1"
license = {file = "LICENSE"}
readme = "README.md"
authors = [
  {name = "Stephen Lane-Walsh", email = "slwalsh@psfc.mit.edu"},
]
requires-python = ">= 3.7"
dependencies = [
  "numpy",
]
